### PR TITLE
Feature/service start stop

### PR DESCRIPTION
**Pull request by codeclout**
- Addresses issue #16 
- Allows users to start / stop services such as a cache store

To test:

- spin up a standalone Redis process
- spin up the example app
- you should see the redis connection take place `onPreStart` (called before the connection listeners are started)

- send the `SIGINT` event
- the redis connection should quit `onPostStop` (called after the connection listeners are stopped)

### CODE REVIEW

**Comment by adslaton** [comment]
I thought about this further... What is an example use case for this feature?

**Comment by niahmiah** [comment]
I was wondering the same thing.... halo plugins already do this

**Comment by codeclout** [comment]
@niahmiah - correct this feature simply exposes the `onPreStop` and `onPostStop` events to the config. Essentially you'd pass an array of objects where each object would contain a `start` and `stop` method that would be called at the appropriate time.

**Comment by codeclout** [comment]
@adslaton - an example would be if I wanted to create a db connection before connections to hapi were allowed, I'd pass that logic as the start method and closing that connection as the stop method.

**Comment by niahmiah** [comment]
I still don't understand. This seems to imply that your services are not hapi plugins. Why would we use hapi that way?

I will defer to AD for approval.

**Comment by davidlumpkinturner** [comment]
the basis for this makes sense to me.  being able to control start and stop of hapi along with other services is something that we should be doing on our apps.  for example, consider this lib being used as a part of different app.

`
db.start()
  .then(() => {
    redis.start();
  })
  .then(() => {
    hapi.start();
  });

function stopServices() {
    hapi.stop()
      .then(() => {
        redis.stop();
      })
      .then(() => {
        db.stop();
        process.exit();
      })
}

process.on('SIGINT', stopServices);

process.on('SIGTERM', stopServices);
`

**Comment by adslaton** [comment]
Can you demo this to Ian and myself?

**Comment by jamsyoung** [comment]
Closing, this is over 2 years old and 66% of the people invovled do not work here anymore.

**Pull request closed without merging**
